# Generated by Django 2.0.6 on 2018-06-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('FechaCreacion', models.DateField()),
                ('Upload', models.FileField(upload_to='')),
            ],
        ),
    ]
