# Generated by Django 2.0.6 on 2018-06-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='FechaCreacion',
            field=models.DateField(verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='Upload',
            field=models.FileField(upload_to='', verbose_name='Archivo'),
        ),
    ]
