# Generated by Django 2.0.6 on 2018-06-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_auto_20180605_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='FechaCreacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
